name: Build & Deploy Pages

on:
  workflow_dispatch: {}
  schedule:
    # UTC = 北京时间 - 8 小时；整点后 1 分钟触发
    - cron: "1 2 * * *"    # 北京 10:01
    - cron: "1 6 * * *"    # 北京 14:01
    - cron: "1 10 * * *"   # 北京 18:01
    - cron: "1 14 * * *"   # 北京 22:01
permissions:
  contents: write   # 允许回推 price_history.txt
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitor
        env:
          ARING_TOKEN: ${{ secrets.ARING_TOKEN }}
        run: |
          python app/monitor.py
          test -f site/index.html

      # 将新增/变更的历史文件提交回 main 分支
      - name: Commit updated price_history.txt back to main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add price_history.txt
          if git diff --cached --quiet; then
            echo "No changes in price_history.txt"
          else
            git commit -m "chore: update price history [skip ci]"
            git push origin HEAD:main
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
